import { motion } from "framer-motion";
import "../../../style/SvgStyles.css";

export default function BetterComp({
  svgParentVariants = { initial: {}, animate: {}, transition: {} },
  svgVariants = { initial: {}, animate: {}, transition: {} },
  classSetter,
}) {
  return (
    <motion.svg
      variants={svgParentVariants}
      initial="initial"
      animate="animate"
      transition="transition"
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      x="0px"
      y="0px"
      viewBox="0 0 247.8 237"
      enable-background="new 0 0 247.8 237"
      xml:space="preserve"
      className={classSetter}
      key="pathComp"
    >
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M168.1,189.2c1.3-2.3,2.6-4.6,3.9-6.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M185.6,204.2c0.7-2.9,1.4-5.9,2.1-8.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M215.3,200.4c-1.3-3.5-2.6-6.9-4-10.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M206.7,175.2c-1.1,2-2.2,4-3.4,5.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M219.8,196.9c0.7-2.9,1.4-5.9,2.1-8.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M243.3,183.3c0.7,1.7,1.4,3.4,2,5.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M109.2,195.9c-1.9,3.4-3.8,6.7-5.7,10.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M123,208.9c0,0.1-0.1,0.1-0.1,0.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M123,208.9c-0.7,2.9-1.4,5.9-2.1,8.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M100.7,190.3c-0.4,3-0.8,5.9-1.2,8.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M88.2,177.6c-1.1,2-2.3,4-3.4,6"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M122.7,185.9c1,1.6,2,3.3,3,4.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M147.9,215.4c-1.3-3.5-2.6-6.9-4-10.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M138.7,188.4c-1,1.7-1.9,3.4-2.9,5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M153.3,202.9c0-0.1,0.1-0.1,0.1-0.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M153.5,202.7c-0.7,2.9-1.4,5.9-2.1,8.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M176.4,198.5c1.3,3.5,2.6,6.9,4,10.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M117.8,171.8c-1,1.7-1.9,3.4-2.9,5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M130.9,184.4c0-0.1,0.1-0.1,0.1-0.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M131,184.2c-0.5,2.3-1,4.5-1.6,6.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M153.6,178.8c0.7,1.8,1.4,3.6,2,5.3"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M69.7,64.6c0,0.2-1.1,0.2-1.1,0.4c-0.6,0.4-0.1,0.4-0.4,1.1
     c-0.2,0.5,0.3,0.9-0.2,1.3c-0.2,0.2,0.2,1.4,0,1.6l-0.7,92.7L206,134.5l1.5-92.8L69.7,64.6z"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M185.7,125.5c5.1-3.4,4.8-2.7,7.8-14.2c1.8-7.1,2.7-14.4,3-21.7
     c0.7-14.6-1.1-29.4-5.5-43.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M69.2,150.3c40.3,3.2,81.5-5.6,116.9-25"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M204.6,134.4c-3.7-4.6-8.4-8.4-13.7-10.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M87.8,177.8c7.1-1.5,14.1-3,21.2-4.5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M119.2,170.7c6.7-1.5,13.4-3,20.2-4.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M176.6,158.2c-8.1,1.7-16.2,3.4-24.2,5.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M185.8,156.2c6.9-1.5,13.8-3,20.7-4.6"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M108.7,195.9c4.8,4.3,9.6,8.5,14.4,12.7"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M100.9,190.2c-4.4-4-8.8-8.1-13.3-12"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M230.3,170.1c5.1,4.5,7.9,7.4,13,11.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M221.9,163.2c-3.9-3.5-7.8-7-11.8-10.5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M123.1,208.5c-0.2,0-0.4,0.1-0.7,0.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M139.8,205.1c-4.9,1-9.8,2-14.7,3"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M153.7,202.2c7.6-1.6,15.3-3.3,22.9-5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M210.6,190.4c-7.8,1.6-15.6,3.3-23.3,4.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M221.6,188c7.4-1.6,14.8-3.2,22.2-4.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M108.8,195.9c6.2-1.3,12.4-2.7,18.6-4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M138.1,188.8c7.9-1.6,13-2.7,20.9-4.5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M187.4,179.2c-4.9,1-9.9,2.1-14.8,3.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M206.3,175.3c8-1.7,15.9-3.4,23.9-5.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M100.3,190.2c7.8-1.6,14.8-3.1,22.6-4.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M134.8,182.6c6.2-1.4,12.5-2.8,18.7-4.3"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M189.1,170.2c-8.2,1.8-15,3.3-23.1,5.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M222,163.5c-6,1.2-12,2.3-18,3.6"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M142.8,202.1c-3.3-3-6.5-6-9.8-9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M123.1,185.8c-4.6-4.1-9.1-8.2-13.8-12.3"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M138.2,188.8c5.1,4.6,10.2,9.2,15.4,13.7"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M130.2,182.7c-4.2-3.7-8.4-7.4-12.6-11.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M163.9,186.3c4.2,3.7,8.4,7.5,12.6,11.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M153.6,178.2c-4.4-4-8.8-7.9-13.3-11.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M172.8,183.2c4.4,4,8.9,7.9,13.4,11.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M165,175.9c-4.5-4-9-8-13.6-12"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M208.8,187.3c-3.2-2.9-6.5-5.8-9.7-8.7"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M190.2,170.6c-4-3.5-8-7-12-10.5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M221.7,188.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M221.9,188.1c-1.3-1.2-9.6-8.3-11-9.4c-1.5-1.1-2.9-2.5-4.3-3.7"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M199,167.5c-4.4-4-8.4-7.6-12.9-11.5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M102.4,211.8c8.8,8,22.1,9.5,33.5,9c3.6-0.2,7.3-0.6,10.9-1.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M71.1,174c8,10.8,16.5,21.3,25.3,31.4"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M67.8,161c0.9-3.5,1.3-7.1,1.3-10.7"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M151.4,164.7c-1,1.7-1.9,3.4-2.9,5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M163.3,182c0.1-1.9,1.2-3.6,1.2-5.6"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M189.9,170.9c0.7,1.9,1.5,3.9,2.2,5.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M186.1,156.6c-1,1.7-1.9,3.4-2.9,5"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M200,168.6C199.4,171.2,199.8,169.4,200,168.6
     c-0.6,2.6-1.2,5.2-1.8,7.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M223.9,168.6c-0.6-1.5-1.2-3.1-1.8-4.6"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M213.5,134.6c8.8-30.9,8.5-64.4-1.1-95.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M242.7,180.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M238.8,175.1"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M230.7,164.1c-5.8-7.8-11.7-15-17.5-22.8"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M209.9,33.6C187.3,15,158.4,4,129.1,3s-58.9,7.8-82.8,24.8
     c-24,17.1-42.7,43.8-43.5,73.3c-0.5,20.4,7.5,40.4,19.6,56.8c10.6,14.3,24,26.3,38.5,36.3c7.5,5.2,14,12.7,21.1,18.5
     c7.6,6.2,4.7,3.8,12.3,9.7l0.2,0.2c15,12.9,30,16,48.2,11.7c27.7-6.4,53.4-13.4,80.9-19.9c7.1-1.5,10-3,16.4-6.3"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M239.1,208.6c7.2-3.4,8.2-12.3,7.2-19.9c-0.3-2.8-0.3-0.4-0.7-3.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M151.3,218.9c14.6-2.8,28.8-7.5,43.1-11.6c7.3-2.1,14.5-4.2,21.8-6.3
     c7-2,14.2-3.8,21.2-6.1c2.9-1,6.2-2.4,7.6-5.4c1.2-2.4,1-5.1-0.6-7.5l-0.3-0.5c-10.5-13.7-19.3-25.2-29.8-38.9"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M197.8,177.1c-8.1,1.7-16.2,3.4-24.2,5.2"
      />
            <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
        d="M222.7,165.1c0.7,1.8,1.3,3.6,2,5.4"
      />
    </motion.svg>
  );
}
