import { motion } from "framer-motion";
import "../../../style/SvgStyles.css";

export default function BetterCube({ svgParentVariants = { initial: {}, animate: {}, transition: {} }, svgVariants = { initial: {}, animate: {}, transition: {} }, classSetter }) {

  return (
    <motion.svg
    variants={svgParentVariants}
    initial="initial"
    animate="animate"
    transition="transition"
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      x="0px"
      y="0px"
      viewBox="0 0 220.5 194"
      enable-background="new 0 0 220.5 194"
      xmlSpace="preserve"
      className={classSetter}
      key="pathCube"
    >
      <g>
        <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M147.8,11.6L60.9,37.2c-1.8-1-7.8-4.2-14.8-8L16.5,11.6H147.8z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M57.2,43.3v61.9L42,120.4L13.8,19.5v-2.1c0,1.3,16.5,10.6,29.5,17.6
     L57.2,43.3z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M37.8,123.6L9.6,151.9V22.7L37.8,123.6z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M206.3,174.6L174,141.4L212.9,47v134.5l-6.2-6.5L206.3,174.6z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M211.8,40.2h-60.4l15.1-25.9L211.8,40.2z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M209.7,45l-38.9,94.3l-4.5-4.6l-41.2-42L151.8,45H209.7L209.7,45z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M42.1,125.7l15.2-15.2v69.3L13.8,154L42.1,125.7z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M160.5,14.2l-14.5,26h-11.4L160.5,14.2z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M155.7,14.3l-25.9,25.9l-61-0.2L155.7,14.3z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M64,45.2l61.1,0.2l-62,62V45.2H64z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M202.8,182.6H74.2l14.5-25.9l32.2-57.8l0,0l41.2,42l4.5,4.6
     l32.3,33.2l0,0L202.8,182.6z"
        />
      <motion.path
          variants={svgVariants}
          initial="initial"
          animate="animate"
          transition="transition"
          fill="none"
          stroke="var(--primarySvgColor)"
          strokeWidth="var(--primarySvgWidth)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeMiterlimit="10"
          d="M138.6,49.7l-26.7,47.7v0.1l-32.2,57.6L65.2,181v-69.3l62-62
     L138.6,49.7z"
        />
      </g>
    </motion.svg>
  );
}
